fragment ThoughtsParts on Thoughts {
  __typename
  title
  order
  tags
  body
}

fragment ProjectsParts on Projects {
  __typename
  title
  description
  techStack
  status
  category
  github
  websiteUrl
  order
  body
}
